version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-auth}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-auth}
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-auth} -d $${POSTGRES_DB:-auth_db}"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth_app
    env_file:
      - auth-service/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    volumes:
      - ./auth-service:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
